version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
  pre_build:
    commands:
      - cd  $CODEBUILD_SRC_DIR/
      - go test ./... -v -short -p 1 -cover
  build:
    commands:
      - echo Building GO code...
      - cd  $CODEBUILD_SRC_DIR/
      - go build -o toy-robot .
artifacts:
  files:
    - toy-robot

